Add missing libvndfwk_detect_jni.qti.so
10-14 23:24:50.903  2737  3343 I qtidataservices: Rejecting re-init on previously-failed class java.lang.Class<com.qualcomm.qti.VndFwkDetect>: java.lang.UnsatisfiedLinkError: dlopen failed: library "libvndfwk_detect_jni.qti.so" not found
10-14 23:24:50.903  2737  3343 I qtidataservices:   at void java.lang.Runtime.loadLibrary0(java.lang.ClassLoader, java.lang.Class, java.lang.String) (Runtime.java:1082)
10-14 23:24:50.903  2737  3343 I qtidataservices:   at void java.lang.Runtime.loadLibrary0(java.lang.Class, java.lang.String) (Runtime.java:1003)
10-14 23:24:50.903  2737  3343 I qtidataservices:   at void java.lang.System.loadLibrary(java.lang.String) (System.java:1661)
10-14 23:24:50.903  2737  3343 I qtidataservices:   at void com.qualcomm.qti.VndFwkDetect.<clinit>() (VndFwkDetect.java:40)
10-14 23:24:50.903  2737  3343 I qtidataservices:   at boolean com.qualcomm.qti.cne.relay.WlanStaInfoRelay$CountryCodeRetriever.getIsVendorEnhancedFramework() (WlanStaInfoRelay.java:540)
10-14 23:24:50.903  2737  3343 I qtidataservices:   at java.lang.String com.qualcomm.qti.cne.relay.WlanStaInfoRelay$CountryCodeRetriever.retrieveCountryCode() (WlanStaInfoRelay.java:605)
10-14 23:24:50.903  2737  3343 I qtidataservices:   at void com.qualcomm.qti.cne.relay.WlanStaInfoRelay$4.onCommand(android.os.Bundle) (WlanStaInfoRelay.java:285)
10-14 23:24:50.903  2737  3343 I qtidataservices:   at boolean com.qualcomm.qti.cne.hwinterface.NativeHalServerCallback$CommandWrapper.handleMessage(android.os.Message) (NativeHalServerCallback.java:210)
10-14 23:24:50.903  2737  3343 I qtidataservices:   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
10-14 23:24:50.903  2737  3343 I qtidataservices:   at boolean android.os.Looper.loopOnce(android.os.Looper, long, int) (Looper.java:205)
10-14 23:24:50.903  2737  3343 I qtidataservices:   at void android.os.Looper.loop() (Looper.java:294)
10-14 23:24:50.903  2737  3343 I qtidataservices:   at void android.os.HandlerThread.run() (HandlerThread.java:67)
--------- beginning of crash
10-14 23:24:50.904  2737  3343 E AndroidRuntime: FATAL EXCEPTION: NativeReceiver
10-14 23:24:50.904  2737  3343 E AndroidRuntime: Process: .qtidataservices, PID: 2737
10-14 23:24:50.904  2737  3343 E AndroidRuntime: java.lang.NoClassDefFoundError: com.qualcomm.qti.VndFwkDetect
10-14 23:24:50.904  2737  3343 E AndroidRuntime: 	at com.qualcomm.qti.cne.relay.WlanStaInfoRelay$CountryCodeRetriever.getIsVendorEnhancedFramework(WlanStaInfoRelay.java:540)
10-14 23:24:50.904  2737  3343 E AndroidRuntime: 	at com.qualcomm.qti.cne.relay.WlanStaInfoRelay$CountryCodeRetriever.retrieveCountryCode(WlanStaInfoRelay.java:605)
10-14 23:24:50.904  2737  3343 E AndroidRuntime: 	at com.qualcomm.qti.cne.relay.WlanStaInfoRelay$4.onCommand(WlanStaInfoRelay.java:285)
10-14 23:24:50.904  2737  3343 E AndroidRuntime: 	at com.qualcomm.qti.cne.hwinterface.NativeHalServerCallback$CommandWrapper.handleMessage(NativeHalServerCallback.java:210)
10-14 23:24:50.904  2737  3343 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-14 23:24:50.904  2737  3343 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
10-14 23:24:50.904  2737  3343 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
10-14 23:24:50.904  2737  3343 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
10-14 23:24:50.904  2737  3343 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libvndfwk_detect_jni.qti.so" not found
10-14 23:24:50.904  2737  3343 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
10-14 23:24:50.904  2737  3343 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
10-14 23:24:50.904  2737  3343 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1661)
10-14 23:24:50.904  2737  3343 E AndroidRuntime: 	at com.qualcomm.qti.VndFwkDetect.<clinit>(VndFwkDetect.java:40)
10-14 23:24:50.904  2737  3343 E AndroidRuntime: 	... 8 more